"""empty message

Revision ID: 739121ab2421
Revises: 1e0392d8dd24
Create Date: 2025-10-30 15:33:21.423444

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '739121ab2421'
down_revision = '1e0392d8dd24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###
